[package]
name = "ss-oled"
version = "1.0.4"
edition = "2021"

[workspace]

members = [
    "ss-oled-ctl",
    "ss-oled-hardware",
    "ss-oled-mpris2",
    "ss-oled-music",
    "ss-oled-simulator",
    "ss-oled-input",
    "ss-oled-tray",
    "ss-oled-gui",
    "ss-oled-engine",
    "ss-oled-windows"
]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ss-oled-hardware = { path = "./ss-oled-hardware", features = ["async"] }


anyhow = "1"
tokio = { version = "1", features = ["time", "net", "io-util", "macros", "rt-multi-thread", "sync"] }
embedded-graphics = "0.8"
tinybmp = "0.6"
config = { version = "0.11", features = ["toml"] }
futures-core = "0.3"
async-stream = "0.3"
futures = "0.3"
linkme = "0.2"
log = "0.4"

ctrlc = "3"
simplelog = "0.12"
pin-project-lite = "0.2"
itertools = "0.14"
chrono = "0.4"
num-traits = "0.2"
ss-oled-input = {path = "./ss-oled-input" }
ss-oled-music = { path = "./ss-oled-music" }
ss-oled-simulator = { path = "./ss-oled-simulator", optional = true }
ss-oled-engine = { path = "./ss-oled-engine", optional = true }
sysinfo = { version = "0.27.7", optional = true }
image  = { version = "0.25", optional = true }
dirs = "6"
ureq = { version = "2", optional = true, features = ["json"] }
serde_json = { version = "1", optional = true }


[target.'cfg(target_os = "windows")'.dependencies]
ss-oled-windows = {path = "./ss-oled-windows"}


[target.'cfg(target_os = "linux")'.dependencies]
ss-oled-mpris2 = { path = "./ss-oled-mpris2", optional = true }
dbus = { version = "0.9", optional = true }
dbus-tokio = { version = "0.7.6", optional = true }

[features]
default = ["dbus-support", "usb"]
dbus-support = ["dbus", "dbus-tokio", "ss-oled-mpris2"]
simulator = ["ss-oled-simulator"]
usb = ["ss-oled-hardware/usb"]
hotkeys = ["ss-oled-input/hotkeys"]
engine = ["ss-oled-engine"]
sysinfo = ["dep:sysinfo"]
image = ["dep:image"]
weather = ["dep:ureq", "dep:serde_json"]
custom = ["dep:ureq", "dep:serde_json"]
lyrics = ["dep:ureq", "dep:serde_json"]
debug = []
