[package]
name = "ss-oled-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gamesense = { git = "https://github.com/not-jan/gamesense" }
anyhow = "1"
ss-oled-hardware = { path = "../ss-oled-hardware", features = ["async"] }
log = "0.4.14"
